services:
  dev:
    build:
      context: .
      dockerfile: docker/Dockerfile.node
      target: dev
    working_dir: /kakeibo
    volumes:
      - type: bind
        source: ./
        target: /kakeibo
      # wrangler の永続化
      - type: bind
        source: /home/node/wrangler-data
        target: /home/node/.config
      - type: bind
        source: ./docker/.bashrc
        target: /home/node/.bashrc
    ports:
      - '3000:3000'
      - '4983:4983'
      - '2222:2222'
    environment:
      LANG: ja_JP.UTF-8
      LC_CTYPE: ja_JP.UTF-8
      SSH_PUB_KEY: ${SSH_PUB_KEY}